Add DEFAULT_MAXLIFE_VALUE and DEFAULT_MAXLIFE_UNIT config params
bepasty/bepasty-server pull request #322
Opened 2024-01-25 18:22 UTC by lhaeger

This hopefully may fix https://github.com/bepasty/bepasty-server/issues/282

Not a python developer myself, yet gave it a shot. Please forgive my ignorance, but I really need this...

2024-01-25 19:05 UTC, ThomasWaldmann requested changes
Thanks for the PR!

See my suggestions for shorter and more compatible code (e.g. if users have old configs without these entries).

Can you please practically try the code after these changes?

2024-01-26 08:58 UTC, lhaeger commented on src/bepasty/utils/date_funcs.py
>      value_default = '1'
Looks much nicer - but the values from bepasty.conf do not get picked up in the web UI. 

I'm testing with https://hub.docker.com/r/asmaps/bepasty, editing the code in /usr/local/lib/python3.9/site-packages/bepasty/ if that makes a difference. 

Does templates/index.html need some modification, maybe? `<select class="form-control" name="maxlife-unit" size="1">`  seems to always pick the first option, which is "Months"...

2024-01-26 09:11 UTC, ThomasWaldmann commented on src/bepasty/utils/date_funcs.py
>      value_default = '1'
Oh, yes, guess it needs to generate different html, making this a bit more complicated...

2024-01-26 09:15 UTC, lhaeger commented on src/bepasty/utils/date_funcs.py
>      value_default = '1'
And that's where my experience ends, unfortunately. Hopefully someone else can chime in.

I'll probably edit index.html in a custom docker image for now...

2024-01-26 09:17 UTC, ThomasWaldmann commented on src/bepasty/utils/date_funcs.py
>      value_default = '1'
Thinking about whether we could just have a fixed unit (e.g. days) and maybe allow a float value also.

That would be much easier overall, but also require a bigger change in the code and templates. Also, one would need to check the documented api and client code, whether we can do such a change without breaking existing clients.

2024-01-26 10:14 UTC, ThomasWaldmann commented on src/bepasty/utils/date_funcs.py
>      value_default = '1'
Note:

https://github.com/bepasty/bepasty-client-cli that client uses the existing unit/value web api.

2025-10-04 19:00 UTC, ThomasWaldmann commented
@lhaeger see #337.

2025-10-04 19:00 UTC, closed without merging